# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=10)),
                ('bedrooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personinfo.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('liceance_plate', models.CharField(max_length=20)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personinfo.Household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personinfo.Person')),
            ],
        ),
    ]
