# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0003_auto_20171009_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personinfo.Household'),
        ),
    ]
